baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
hasCJKLanguage = true
summaryLength = 200
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

[languages]
  [languages.en]
    title = "AnYang Road"
    subtitle = "~~~ "
    keywords = ""
    copyright = "Copyright@2019 yifanyou"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "AnYang Road"
      logoHomeLink = "/"

    [languages.en.menu]  
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
  [languages.cn]
    title = "安阳路"
    subtitle = "写一点点东西"
    keywords = ""
    copyright = "Copyright@2019 yifanyou"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.cn.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.cn.menu]
      [[languages.cn.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
      [[languages.cn.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
